services:
  - type: web
    name: okaycoin-bot
    env: node
    buildCommand: npm install
    startCommand: node COMPLETE_BOT_CODE.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        fromDatabase: false
